// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yetvycrgcaieimlzualo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlldHZ5Y3JnY2FpZWltbHp1YWxvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1NDY3NzksImV4cCI6MjA2NzEyMjc3OX0.ip5zX9h-H3d3jTObczGLldhoH1cK6LBXOQKrYATXXDE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});